# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "MihMihai"
    versioning-strategy: auto # uses "increase" for apps and "widen" for libraries.
    groups:
      dart:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
