name: flutter_media_metadata
description: A Flutter plugin to read metadata of media files.
version: 1.0.2
homepage: https://github.com/alexmercerind/flutter_media_metadata
repository: https://github.com/alexmercerind/flutter_media_metadata
documentation: https://github.com/alexmercerind/flutter_media_metadata/blob/master/README.md

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  js: ">=0.6.4 <0.8.0"
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ">=2.0.1 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmercerind.flutter_media_metadata
        pluginClass: FlutterMediaMetadataPlugin
      windows:
        pluginClass: FlutterMediaMetadataPlugin
      linux:
        pluginClass: FlutterMediaMetadataPlugin
      ios:
        pluginClass: FlutterMediaMetadataPlugin
      macos:
        pluginClass: FlutterMediaMetadataPlugin
      web:
        pluginClass: MetadataRetriever
        fileName: src/flutter_media_metadata_web.dart
